[package]
name = "rust_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
fast_image_resize = "4" # high-quality, fast resize
rgb = "0.8"
# Optional: better panic messages in dev
console_error_panic_hook = "0.1"

[features]
default = []
